### ISSUE TITLE
jupyter integration

### ISSUE THREAD

**Issue by jcvillaquira** [mfussenegger/nvim-dap-python#80] opened 2022-12-21 22:15 UTC
I have a question about the python debugger. I want to setup my working environment in VIM. To code in jupyter I am using `vim-slime` to connect to an ipython session and use ipdb to debug. However it is not the best debugging experience and I would love to be able to use dap (it has a beautiful integration with AstronVIM).

Is this possible right now? Or is it easy to implement? 

This is the only thing keeping me using VS Code, since it manages jupyter debugging pretty well.

Regards!

**Comment by mfussenegger** [comment] 2022-12-22 09:36
> Is this possible right now?

An option could be to run debugpy within the jupyter notebook using the APIs described here: https://github.com/microsoft/debugpy/#enabling-debugging and then attach to it.

Using jupyter's own debugging mechanism is afaik currently not possible, and would require a custom implementation

> Or is it easy to implement?

It looks like jupyter has its own transport (zeromq?) and wraps DAP messages in their own requests: https://jupyter-client.readthedocs.io/en/stable/messaging.html#debug-request

On a first glance it seems as if the vscode-jupyter extension takes care of translating that: https://github.com/microsoft/vscode-jupyter/blob/c0b8e355de960f0ba393235066059167aeadb3b7/src/notebooks/debugger/kernelDebugAdapterBase.ts

It should be possible to do something like that with nvim-dap, but not without some effort. It's also out-of-scope for nvim-dap-python and would probably deserve it's own extension

**Comment by mmngreco** [comment] 2022-12-27 16:16
I never tried but I thinkg that using jupytext, https://github.com/goerz/jupytext.vim,  you can open a ipynb, convert it to python script underhood and then you should be able to debug it as if it was a regular python script.

**Comment by jcvillaquira** [comment] 2022-12-27 16:20
Yes, I can do that. The problem is that I am not able to debug a single cell. To debug I would have to run the whole file, but this is not ideal since, for example, I may want to debug the last cell without running the first part of the notebook/script. I am currently using `jupytext` and sending cells to an REPL.

**Comment by mmngreco** [comment] 2022-12-29 18:48
Oh, I see the point! I concur with @mfussenegger, I think that is a very concrete implementation. 

A bit offtopick, I drop here some ideas in case it could help: Personally, I would execute the whole file many times or, if I really needed, I would create a [MRE](https://stackoverflow.com/help/minimal-reproducible-example). A quick way to get it done is using [dill](https://github.com/uqfoundation/dill) e.g. https://stackoverflow.com/a/35296032. I'm not a fan of notebooks as it's easy to mess it up and/or forget good practises, so I would check if there is a design problem on it (lack of class or high level function, or a utils module to import function from) .

**Comment by mfussenegger** [comment] 2023-02-17 14:31
Closing this here since it's out of scope for nvim-dap-python, but it would be really cool to see a nvim-jupyter extension that includes dap support.

**Closed by mfussenegger** 2023-02-17 14:31 UTC
